FROM php:8.4-cli AS dev

RUN apt-get update && apt-get install -y \
    build-essential \
    zip \
    unzip \
    git \
    curl \
    libzip-dev \
    libonig-dev \
    libssl-dev \
    pkg-config \
    librdkafka-dev \
    libpq-dev \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install zip pdo pdo_pgsql \
    && pecl install rdkafka opentelemetry \
    && docker-php-ext-enable rdkafka opentelemetry

RUN php -m | grep opentelemetry

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

RUN git config --global --add safe.directory /var/www/html

COPY composer.json composer.lock ./

RUN composer install --no-scripts --no-autoloader

COPY . /var/www/html

RUN composer dump-autoload --optimize

CMD ["php", "artisan", "list"]
